

CREATE DATABASE empmanager;
USE empmanager;

CREATE TABLE MST_EMPLOYEE(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  EMPLOYEE_NAME VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MST_SKILL(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SKILL VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MAPPER_EMPLOYEE_SKILL(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_SKILL BIGINT(20),
  FK_EMPLOYEE BIGINT(20),
  CONSTRAINT FOREIGN KEY (FK_EMPLOYEE) REFERENCES MST_EMPLOYEE (ID),
  CONSTRAINT FOREIGN KEY (FK_SKILL) REFERENCES MST_SKILL (ID),
  PRIMARY KEY (ID)
);

INSERT INTO `MST_SKILL` (`SKILL`) VALUES ('Hibernate');
INSERT INTO `MST_SKILL` (`SKILL`) VALUES ('Java');
INSERT INTO `MST_SKILL` (`SKILL`) VALUES ('Spring');
INSERT INTO `MST_SKILL` (`SKILL`) VALUES ('Angular');

INSERT INTO `MST_EMPLOYEE` (`EMPLOYEE_NAME`) VALUES ('Stelan Briyan');
INSERT INTO `MST_EMPLOYEE` (`EMPLOYEE_NAME`) VALUES ('Renuka Piyumal');
INSERT INTO `MST_EMPLOYEE` (`EMPLOYEE_NAME`) VALUES ('Denver Shan');
INSERT INTO `MST_EMPLOYEE` (`EMPLOYEE_NAME`) VALUES ('Manoj Madusanka');

INSERT INTO `MAPPER_EMPLOYEE_SKILL` (`FK_SKILL`, `FK_EMPLOYEE`) VALUES ('1', '1');
INSERT INTO `MAPPER_EMPLOYEE_SKILL` (`FK_SKILL`, `FK_EMPLOYEE`) VALUES ('1', '2');
INSERT INTO `MAPPER_EMPLOYEE_SKILL` (`FK_SKILL`, `FK_EMPLOYEE`) VALUES ('2', '3');
INSERT INTO `MAPPER_EMPLOYEE_SKILL` (`FK_SKILL`, `FK_EMPLOYEE`) VALUES ('1', '4');
INSERT INTO `MAPPER_EMPLOYEE_SKILL` (`FK_SKILL`, `FK_EMPLOYEE`) VALUES ('1', '3');

