

CREATE DATABASE empmanager;
USE empmanager;

CREATE TABLE MST_EMPLOYEE(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  EMPLOYEE_NAME VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MST_SKILL(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  SKILL VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE MAPPER_EMPLOYEE_SKILL(
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  FK_SKILL BIGINT(20),
  FK_EMPLOYEE BIGINT(20),
  CONSTRAINT FOREIGN KEY (FK_EMPLOYEE) REFERENCES MST_EMPLOYEE (ID),
  CONSTRAINT FOREIGN KEY (FK_SKILL) REFERENCES MST_SKILL (ID),
  PRIMARY KEY (ID)
);